### ISSUE TITLE
Android Test badge in README.md is broken

### ISSUE THREAD

**Issue by Raboro** [DHBWorld/DHBWorld#91]
The Badge is trying this url: https://github.com/DHBWorld/DHBWorld/actions/workflows/android.yml, which is no correct anymore, because since 6 months this workflow is not used. Because of that no badge and the alt text is shown in the README:
![image](https://github.com/DHBWorld/DHBWorld/assets/88288557/45d241f5-3de4-4a36-bd31-a11bc0ab0c21)

Should be easy to fix, by just changing the url to the new valid workflow.

**Comment by blitzdose** [comment]
Fixed by removing :)
